spring:
  application:
    name: backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:./uploads/, classpath:/static/

app:
  upload-dir: uploads

# Sa-Token
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

